### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by artloder** [benas/jcql#4]
This is just a suggestion, but _Java Code Query Linter_ seems too specific a name, as linting is only one of its uses. Why not call it something more general like _Java Code Query Language_ (same abbreviation)?

**Comment by fmbenhassine** [comment]
Hi, thank you for this suggestion.

_Java Code Query Language_ was the first name (see afab7972da1617080c5d4ce9cd5cf87004f1bf0c),  but since it still plain SQL, this was a wrong name.

BTW, the current name is also wrong, _Java Code Query Linter_ makes no sense.. I'm struggling to find a good name

> linting is only one of its uses

What are other uses? I think the main goal is to lint java code with SQL

I was thinking for simply renaming it to one of:
- java-linter
- jlinter
- java-code-linter

jlint, lint4j already exist.

Any other suggestion? Any help is appreciated!

**Comment by fmbenhassine** [comment]
> linting is only one of its uses

I think I see what you mean now. If I ask "how many classes are there", I'm not necessarily linting (founding potential problems), I'm just looking for some stats.. Is this what you mean?

If this true, We are right back where we started 😄 and probably _Java Code Query Language_ is a good one, or simply "Java Query Language" (JQL : /dʒeı kju el/ )? It still a structured query language for Java (not to confuse with JPQL)

**Comment by fmbenhassine** [comment]
sql4j? but this would be confusing for a library that facilitates sql for java. Moreover, it's in [here](https://github.com/llorllale/sql4j).

**Comment by fmbenhassine** [comment]
@artloder I've changed the name to the more general _Java Query Language_. 

It's inspired by [gitql](https://github.com/cloudson/gitql) and [textql](https://github.com/dinedal/textql) 

I'm not really convinced with this name because it still SQL.. Here is a true java query language with new syntax and compiler: http://homepages.ecs.vuw.ac.nz/~djp/jql/

So probably if the PoC is successful, the name should be changed to a more general static analysis tool without any reference to query language in the name (probably [will support NoSQL too](https://github.com/benas/jql/wiki/roadmap#in-general)).

What do you think?
